"""empty message

Revision ID: d243841d78fb
Revises: d43259a22dfb
Create Date: 2024-06-01 22:24:13.482778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd243841d78fb'
down_revision = 'd43259a22dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fee_total', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fees')
    # ### end Alembic commands ###
